### PR TITLE
LPS-x OPEN NLP

### PR DESCRIPTION
**Pull request by tinatian**
Hi @lanceji92674957 ,
Please run a diff on DL with this pull.

Thanks.
Tina

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
Hi @slnn,
Please run a diff with pull.

cc @dantewang

Thanks.
Tina.

**Comment by slnn** [comment]
Hi @tinatian 

Here are test results on DL and Login:

Login:

Portal Version | Git Id | Session Count | Mean Time of Log in | Mean Time of Log out
-- | -- | -- | -- | --
BaseLine | b203820 | 44605 | 299 | 89.3
PR-224 | - | 44724 | 283 | 85.1

DL:


Portal Version | Git Id | Session Count | Mean Time of Log in | Mean Time of Add DL File
-- | -- | -- | -- | --
BaseLine | b203820 | 21580 | 278 | 384
PR-224 | - | 21376 | 421 | 505



From the heap dumo of DL, this pull reduced the Retained Size of the OpenNLPDocumentAssetAutoTaggerImpl object, and no SentenceModel object be found in the heap dump.

Please see these screenshots of the heap dump:

Search OpenNLPDocumentAssetAutoTaggerImpl object in the heap dump of baseline:

BaseLine-DL-HeapDump-OpenNLPDocumentAssetAutoTaggerImpl-screenshot

Search OpenNLPDocumentAssetAutoTaggerImpl object in the heap dump of pr:

PR-224-DL-HeapDump-OpenNLPDocumentAssetAutoTaggerImpl-screenshot


Search SentenceModel object in the heap dump of baseline:

BaseLine-DL-HeapDump-SentenceModel-screenshot

Search SentenceModel object in the heap dump of pr:

PR-224-DL-HeapDump-SentenceModel-screenshot


Lily

**Comment by tinatian** [comment]
Thanks @slnn!

But it is weird that we decrease the usage of heap dump and the session count goes down, could you please upload the test result of DL?

Tina.

**Comment by slnn** [comment]
Hi @tinatian 

Test results for DL please see here: [PR-224-DL-test results](https://mega.nz/#F!M191DKIR!ADiiz7dcR1r-_7-vrvyilQ)

Regards
Lily

**Pull request closed without merging**
